version: "3"

services:
  zeppelin:
    container_name: "zeppelin"
    image: apache/zeppelin:0.9.0
    ports:
        - 8080:8080
    volumes:
        - ./hdfs:/hdfs
        - ./notebooks:/zeppelin/notebook